---

# File naming
project_name : "Testing"

suffix : 'double_2'
folder : 'experiments_forward_filtered'
trained_folder : 'experiments_forward_filtered_trained'
log_to_file: False


# episode parameters
EPISODES : 2000
EPISODE_STEPS : 4000
SHOW_EVERY : 100
SHOW : True
TEST_EPISODE: 10

# rule based method
# RAND: Random, FCFS: First Come First Serve
RULE : "FCFS"

# DQN parameters
double : True
PER : False

BATCH_SIZE : 64
BUFFER_SIZE : 3000000
TARGET_UPDATE_FREQ : 50000
TAU : 0.0001
LEARNING_FREQ : 1
epsilon : 1  # 0 means no exploration, 1 means only exploration
EPSILON_DECAY : 0.995
MIN_EPSILON : 0.1
LEARNING_RATE : 0.0001
DISCOUNT : 0.95
LEARNING_START : 64

# job parameters
DYNAMIC : False
MAX_DEADLINE : 5000
MAX_OPERATIONS : 3
MIN_OP_TIME : 120.0
MAX_OP_TIME : 240.0

SPEED_SEED : 5
JOB_LIB_SEED : 6
INSTANCE_SEED : 7


# environment parameters
n : 4   # number of upcoming processes seen
m : 2  # window size

FRAME_SKIP : 1

JOBS_TO_COMPLETE : 10
JOBS_TO_GENERATE: 10
CONVEYOR_SIZE : 12
CONVEYOR_POS : [0, 1, 5, 9]
#CONVEYOR_POS : [0, 1, 2, 3]
CONVEYOR_FILL : 0.6

NUMBER_AGENTS : 3
#NUMBER_ABILITIES : 4
ABILITIES : [[1, 2, 3], [1, 2, 3], [1, 2, 3]]

#NUMBER_AGENTS : 2
# NUMBER_ABILITIES : 3
#ABILITIES : [[1, 2, 3], [1, 2, 3]]

JOB_STATUSES : {"waiting": 0,
                "processing": 1,
                "finished": 2,
                }
AGENT_STATUSES : {"idle": 0,
                  "starting job": 1,
                  "processing job": 2,
                  "ready for unload": 3
                  }

average_score : -100000
best_score : -100000

rate : 0.1
min_max : 0.5
unique_no_job : 2
max_steps : 4